#!/usr/bin/python3
import os
import sys
import zipfile

if len(sys.argv) != 2:
	raise Exception("Need to supply directory.")
dirname = sys.argv[1]
if not os.path.isdir(dirname):
	raise Execption("No such directory: %s" % (dirname))

projname = os.path.basename(dirname.rstrip("/")).lower()
with zipfile.ZipFile("%s.zip" % (projname), "w", compression = zipfile.ZIP_DEFLATED) as zfile:
	for extension in [ "GTL", "GTS", "GTO", "GBL", "GBS", "GBO" ]:
		zfile.write("%s/files/Gerber/PCB1.%s" % (dirname, extension), arcname = "%s.%s" % (projname, extension))
	zfile.write("%s/files/Gerber/PCB1.Outline" % (dirname), arcname = "%s.GML" % (projname))
	zfile.write("%s/files/NC Drill/PCB1.TXT" % (dirname), arcname = "%s.TXT" % (projname))
